language: go

go:
  - '1.10.2'

script:
  - go test -v ./hgl
  - go test -v ./hangulize

after_success:
  - mkdir -p build

  # Executable
  - go build -o build/hangulize

  # JavaScript
  - go get -u github.com/gobuffalo/packr/...
  - go get -u github.com/gopherjs/gopherjs
  - packr --compress --input ./hangulize -v
  - gopherjs build ./js -o build/hangulize.js -m -v

deploy:
  provider: releases
  api_key:
    secure: HD/kMnp2djKpx5an8VDpYpkgvTnSM5KnoPkj1obyEe5dhT6mmjBkfsjQMufJ88CzgufZytITohEfaPqlDvrVs7QMc5Ucup0WrOPjnSzNAL/3N8Fqu6I+5KUQ/fGZsaYAOCXct0iuIMreLrDlVy+Q3vQBhKJn6y9wz918wIk7N0ucJMuIOZPffEqDPuErjuSqr1vbAcoPsyiioMmEasI+4h2H/ax8YmmmJub0O8YCyrh/iwQZk/xVBL7O9RU8xZKEDBy0qJPFBFK5atZwORPDQhh1dKx5q97Ip/GOz43rh8bZrTd2QVDDSqJmVv52UX2dpFo5Pzg9wO6t/sNdIgeuLH5vHc39kt4H9QJpBdgdcRiGhIbMMAHGW/d75sIBubGAvpTQ9cBZEQ9xgDrr00G8PQVt2SyJeZM2uLx6wv3zirJrk3rpEZFC2Jo+/wJQARwo/bbuPjypzcT6wVdhj3jkidp0N/yXPGQwRoDUNPD119oo9sWGSbdYPLGLPUclcbf2roou+DFZ+kxGorJcmiAS8ZYaL9H5pY6ItW92g7DBVNud/fSMZLwfgxmLN33sGzs5mb7lbKjsVIa2Jqy32hQ6ANmLQMWYcZjXf5tD+jPenwq847K3u8zEmpGJn7/ShGXVKakN+nbFoyyD8tfn3/u2RTDLGjCe7g6DDd1AYnWO5t8=
  file: build/*
  on:
    branch: ci
