language: go

go:
- '1.10.2'

install:
- go get -v -t ./...
- GOOS=windows go get -v -t ./...
- go get -v github.com/gobuffalo/packr/...
- go get -v github.com/mitchellh/gox
- go get -v github.com/gopherjs/gopherjs

script:
- set -e

# Test -----------------------------------------------------------------------
- go test -v ./hgl
- go test -v ./hangulize

# Build ----------------------------------------------------------------------
- mkdir -p build

  # pack bundle
- packr --compress --input ./hangulize -v

  # executable
- |
  gox -arch='amd64' \
      -os='linux darwin windows' \
      -output="build/hangulize_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}" \
      -verbose

  # js
- gopherjs build ./js -o "build/hangulize-${TRAVIS_TAG}.js" -m -v
- rm -f build/*.js.map

deploy:
  provider: releases
  on:
    tags: true

  skip_cleanup: true
  file: build/*
  file_glob: true

  api_key:
    secure: Dx83tKAMHcWJICWG1+UWawAqWum8juHUbUJ6TmUF1JC8omDnbCLlaFDN0mqRIYoNAWoPViKEQoyiqNK1nziwEgD1JA/pYViFrTCjbNqSAWEyFkZ381uPpTEVm3RA0BlyZKAqmHpUyA4EccKKqRRq+FoM9pgvs03KxAZ2B1nz/P9vUlusYfHjI6x4NygFnHtbD845VC7v0Zveod4KgHQ5dKqrW3mG6woOq17OU/7Nt0Y2Ybq6U1Ll8epulp59NVuLKm0zsxK2MXAgPCxaGqbnSKE3qV4bxVq3T5iicu1mYVrjO9jwToGcLK3d6ce30XX/SfrZ3M2t3qOgKKx57MhJZQeL14L/xqCEKcHLrtJT1fsq4LKtGJF+nx1wtG25UcvIbaoL7ifGYbzXQytekYpydBSMTsC5c8cu7wG2knSdGeTp7V2fTD8AWROd65XLNEQdwvpgUDqNfs1cp82IDS0XkxZZirOqXmZZdO2BOrt44WZTX/eG5HeRri0kIJ136VigUr4BDqlV1jxMAq4OwO4w+dZsdKP21pDHq8B2rhSkhQIpfGVEgA8rdHs0YcC9IyJkN3SL6NeuEFukrL+agtOzHNM5mTM+sKuxZmRTq4a03EK8LMo7+oSsuphF4g7RQmehwOT9nKjmRxTXKWKjOXkE7joYSYNh9AsxDnDgGZrOjCg=
